package io.kevs.rabbitmq.ksp.options

import com.google.devtools.ksp.processing.SymbolProcessorEnvironment

data class KevsKspRabbitMqOptions(
    val eventSubscribers: EventSubscriberOptions,
    val eventCollectors: CollectorOptions,
    val springOptions: SpringOptions
) {

    class EventSubscriberOptions(
        val create: Boolean
    )

    class CollectorOptions(
        val create: Boolean
    )

    class SpringOptions(
        val createConfigurationBean: Boolean,
        val configurationBeanClass: String,
        val configurationBeanPackage: String
    )

    companion object {
        fun SymbolProcessorEnvironment.parseKevsKspOptions(): KevsKspRabbitMqOptions {
            return KevsKspRabbitMqOptions(
                EventSubscriberOptions(
                    options["io.kevs.rabbitmq.event-subscribers.create"]?.toBooleanStrict() ?: false,
                ),
                CollectorOptions(
                    options["io.kevs.rabbitmq.event-collectors.create"]?.toBooleanStrict() ?: false,
                ),
                SpringOptions(
                    options["io.kevs.rabbitmq.spring.create-configuration-bean"]?.toBooleanStrict() ?: false,
                    options["io.kevs.rabbitmq.spring.configuration-bean-class"] ?: "KevsRabbitMqAutogeneratedConfiguration",
                    options["io.kevs.rabbitmq.spring.configuration-bean-package"] ?: "io.kevs.application.configuration"
                )
            )
        }
    }
}